[tool.briefcase]
project_name = "tmoons"
bundle = "io.ycle.teenmoons"
version = "0.0.1"
url = "https://teenmoons.ycle.io/tmoons"
license = "MIT license"
author = 'frankjardel'
author_email = "jardel.ycle@gmail.com"

[tool.briefcase.app.tmoons]
formal_name = "tmoons"
description = "My first application"
icon = "src/tmoons/resources/tmoons"
sources = [
    'src/tmoons',
    'driver',
]
requires = [
    'evdev>=1.2.0',
    'pyusb>=1.0.2',
    'PyYAML>=5.2',
    'pynput==1.2.0'
]


[tool.briefcase.app.tmoons.macOS]
requires = [
    'toga-cocoa>=0.3.0.dev20',
]

[tool.briefcase.app.tmoons.linux]
requires = [
    'toga-gtk>=0.3.0.dev20',
    'driver',
]
system_requires = [
    'libgirepository1.0-dev',
    'libcairo2-dev',
    'libpango1.0-dev',
    'libwebkitgtk-3.0-0',
    'gir1.2-webkit-3.0',
]

[tool.briefcase.app.tmoons.windows]
requires = [
    'toga-winforms>=0.3.0.dev20',
]

# Mobile deployments
[tool.briefcase.app.tmoons.iOS]
requires = [
    'toga-iOS>=0.3.0.dev20',
]

[tool.briefcase.app.tmoons.android]
requires = [
    'toga-android>=0.3.0.dev20',
]
